Implement similar logic to pnpm installation for ui, remove cache from Dockerfile prod, separate install/remove npm-pnpm-yarn to faster caching and shared use

diff --git a/Dockerfile.ci b/Dockerfile.ci
--- a/Dockerfile.ci
+++ b/Dockerfile.ci
@@ -1236,11 +1236,13 @@ function install_yarn_dependencies_from_branch_tip() {
     echo
     local TEMP_AIRFLOW_DIR
     TEMP_AIRFLOW_DIR=$(mktemp -d)
+
     # Download the source code from the specified branch
     set -e
     set -x
     curl -fsSL "https://github.com/${AIRFLOW_REPO}/archive/${AIRFLOW_BRANCH}.tar.gz" | \
         tar xz -C "${TEMP_AIRFLOW_DIR}" --strip 1
+
     # Install Yarn dependencies
     cd "${TEMP_AIRFLOW_DIR}/airflow/www"
     yarn install --frozen-lockfile
@@ -1257,49 +1259,123 @@ function install_yarn_dependencies_from_branch_tip() {
     cp -r ./node_modules $YARN_CACHE_DIR/
     echo "${COLOR_BLUE}Yarn packages copied successfully${COLOR_RESET}"
     set +x
+
     # Clean up
-    remove_npm_and_yarn
     rm -rf "${TEMP_AIRFLOW_DIR}"
     set +e
 }
 
-function install_npm_and_yarn() {
+common::get_colors
+
+install_yarn_dependencies_from_branch_tip
+EOF
+
+# The content below is automatically copied from scripts/docker/install_pnpm_dependencies_from_branch_tip.sh
+COPY <<"EOF" /install_pnpm_dependencies_from_branch_tip.sh
+#!/usr/bin/env bash
+
+. "$( dirname "${BASH_SOURCE[0]}" )/common.sh"
+
+: "${AIRFLOW_REPO:?Should be set}"
+: "${AIRFLOW_BRANCH:?Should be set}"
+
+function install_pnpm_dependencies_from_branch_tip() {
     echo
-    echo "${COLOR_BLUE}Installing npm and yarn${COLOR_RESET}"
+    echo "${COLOR_BLUE}Installing pnpm dependencies from ${AIRFLOW_BRANCH}. It is used to cache dependencies${COLOR_RESET}"
+    echo
+    local TEMP_AIRFLOW_DIR
+    TEMP_AIRFLOW_DIR=$(mktemp -d)
+
+    # Download the source code from the specified branch
+    set -e
+    set -x
+    curl -fsSL "https://github.com/${AIRFLOW_REPO}/archive/${AIRFLOW_BRANCH}.tar.gz" | \
+        tar xz -C "${TEMP_AIRFLOW_DIR}" --strip 1
+
+    # Install pnpm dependencies
+    cd "${TEMP_AIRFLOW_DIR}/airflow/ui"
+    pnpm install --frozen-lockfile --config.confirmModulesPurge=false
+    set +x
+    set +e
+    echo "${COLOR_BLUE}pnpm dependencies installed successfully${COLOR_RESET}"
+
+    # Copy pnpm packages to the .pnpm-cache directory
+    echo
+    echo "${COLOR_BLUE}Copying pnpm packages to the ${PNPM_CACHE_DIR} directory${COLOR_RESET}"
+    echo
+    set -e
+    set -x
+    cp -r ./node_modules $PNPM_CACHE_DIR/
+    echo "${COLOR_BLUE}pnpm packages copied successfully${COLOR_RESET}"
+    set +x
+
+    # Clean up
+    rm -rf "${TEMP_AIRFLOW_DIR}"
+    set +e
+}
+
+common::get_colors
+
+install_pnpm_dependencies_from_branch_tip
+EOF
+
+# The content below is automatically copied from scripts/docker/install_npm_pnpm_yarn.sh
+COPY <<"EOF" /install_npm_pnpm_yarn.sh
+#!/usr/bin/env bash
+. "$( dirname "${BASH_SOURCE[0]}" )/common.sh"
+
+function install_npm_pnpm_yarn() {
+    echo
+    echo "${COLOR_BLUE}Installing npm, pnpm and yarn${COLOR_RESET}"
     echo
     set -e
     set -x
     # Install npm
     apt-get update
     apt-get install -y npm
+    # Install pnpm
+    npm install -g pnpm
     # Install yarn
     npm install -g yarn
-    echo "${COLOR_BLUE}npm and yarn installed successfully${COLOR_RESET}"
+    echo "${COLOR_BLUE}npm, pnpm and yarn installed successfully${COLOR_RESET}"
     set +x
     set +e
 }
 
-function remove_npm_and_yarn() {
+common::get_colors
+
+install_npm_pnpm_yarn
+EOF
+
+
+# The content below is automatically copied from scripts/docker/remove_npm_pnpm_yarn.sh
+COPY <<"EOF" /remove_npm_pnpm_yarn.sh
+#!/usr/bin/env bash
+. "$( dirname "${BASH_SOURCE[0]}" )/common.sh"
+
+function remove_npm_pnpm_yarn() {
     echo
-    echo "${COLOR_BLUE}Removing npm and yarn${COLOR_RESET}"
+    echo "${COLOR_BLUE}Removing npm, pnpm and yarn${COLOR_RESET}"
     echo
     set +e
     set -x
-    # Remove yarn
     npm cache clean --force
+    # Remove pnpm
+    npm uninstall -g pnpm
+    # Remove yarn
     npm uninstall -g yarn
     # Remove npm
     apt-get remove -y npm
-    echo "${COLOR_BLUE}npm and yarn removed successfully${COLOR_RESET}"
+    echo "${COLOR_BLUE}npm, pnpm and yarn removed successfully${COLOR_RESET}"
     set +x
     set -e
 }
 
 common::get_colors
 
-install_npm_and_yarn
-install_yarn_dependencies_from_branch_tip
+remove_npm_pnpm_yarn
 EOF
+
 
 ##############################################################################################
 # This is the build image
@@ -1462,8 +1538,7 @@ RUN echo "Airflow version: ${AIRFLOW_VERSION}"
 
 # Copy all scripts required for installation - changing any of those should lead to
 # rebuilding from here
-COPY --from=scripts install_packaging_tools.sh install_airflow_dependencies_from_branch_tip.sh \
-    common.sh install_yarn_dependencies_from_branch_tip.sh /scripts/docker/
+COPY --from=scripts install_packaging_tools.sh install_airflow_dependencies_from_branch_tip.sh common.sh /scripts/docker/
 
 # We are first creating a venv where all python packages and .so binaries needed by those are
 # installed.
@@ -1481,7 +1556,14 @@ RUN bash /scripts/docker/install_packaging_tools.sh; \
         bash /scripts/docker/install_airflow_dependencies_from_branch_tip.sh; \
     fi
 
-# Yarn cache
+#
+# yarn and pnpm installation and caching
+#
+# Install npm, pnpm and yarn
+COPY --from=scripts install_npm_pnpm_yarn.sh /scripts/docker/
+RUN bash /scripts/docker/install_npm_pnpm_yarn.sh
+
+# yarn cache
 ARG AIRFLOW_PRE_CACHED_YARN_PACKAGES="true"
 ENV AIRFLOW_PRE_CACHED_YARN_PACKAGES=${AIRFLOW_PRE_CACHED_YARN_PACKAGES}
 COPY --from=scripts install_yarn_dependencies_from_branch_tip.sh /scripts/docker/
@@ -1494,6 +1576,22 @@ RUN if [[ ${AIRFLOW_PRE_CACHED_YARN_PACKAGES} == "true" ]]; then \
         bash /scripts/docker/install_yarn_dependencies_from_branch_tip.sh; \
     fi
 
+# pnpm cache
+ARG AIRFLOW_PRE_CACHED_PNPM_PACKAGES="true"
+ENV AIRFLOW_PRE_CACHED_PNPM_PACKAGES=${AIRFLOW_PRE_CACHED_PNPM_PACKAGES}
+COPY --from=scripts install_pnpm_dependencies_from_branch_tip.sh /scripts/docker/
+
+ENV PNPM_CACHE_DIR="${AIRFLOW_USER_HOME_DIR}/.pnpm-cache"
+RUN mkdir -p "${PNPM_CACHE_DIR}" && \
+    chown -R "airflow:0" "${PNPM_CACHE_DIR}"
+# We are installing pnpm dependencies here to make sure they are cached in the layer
+RUN if [[ ${AIRFLOW_PRE_CACHED_PNPM_PACKAGES} == "true" ]]; then \
+        bash /scripts/docker/install_pnpm_dependencies_from_branch_tip.sh; \
+    fi
+
+# Remove npm, pnpm and yarn
+COPY --from=scripts remove_npm_pnpm_yarn.sh /scripts/docker/
+RUN bash /scripts/docker/remove_npm_pnpm_yarn.sh
 
 # Here we fix the versions so all subsequent commands will use the versions
 # from the sources
