Include pre-commit script inside docker images, add comment separating scripts and build, include -+e to script

diff --git a/Dockerfile.ci b/Dockerfile.ci
--- a/Dockerfile.ci
+++ b/Dockerfile.ci
@@ -1220,6 +1220,46 @@ COPY <<"EOF" /entrypoint_exec.sh
 exec /bin/bash "${@}"
 EOF
 
+
+# The content below is automatically copied from scripts/docker/install_yarn_dependencies_from_branch_tip.sh
+COPY <<"EOF" /install_yarn_dependencies_from_branch_tip.sh
+#!/usr/bin/env bash
+
+. "$( dirname "${BASH_SOURCE[0]}" )/common.sh"
+
+: "${AIRFLOW_REPO:?Should be set}"
+: "${AIRFLOW_BRANCH:?Should be set}"
+: "${AIRFLOW_SOURCES:?Should be set}"
+
+function install_yarn_dependencies_from_branch_tip() {
+    echo
+    echo "${COLOR_BLUE}Installing Yarn dependencies from ${AIRFLOW_BRANCH}. It is used to cache dependencies${COLOR_RESET}"
+    echo
+    local TEMP_AIRFLOW_DIR
+    TEMP_AIRFLOW_DIR=$(mktemp -d)
+    # Download the source code from the specified branch
+    set +e
+    set -x
+    curl -fsSL "https://github.com/${AIRFLOW_REPO}/archive/${AIRFLOW_BRANCH}.tar.gz" | \
+        tar xz -C "${TEMP_AIRFLOW_DIR}" --strip 1
+    # Install Yarn dependencies
+    cd "${TEMP_AIRFLOW_DIR}/airflow/www"
+    yarn install --frozen-lockfile
+    set +x
+    set -e
+    echo "${COLOR_BLUE}Yarn dependencies installed successfully${COLOR_RESET}"
+    # Clean up
+    rm -rf "${TEMP_AIRFLOW_DIR}"
+}
+
+common::get_colors
+
+install_yarn_dependencies_from_branch_tip
+EOF
+
+##############################################################################################
+# This is the build image
+##############################################################################################
 FROM ${PYTHON_BASE_IMAGE} as main
 
 # Nolog bash flag is currently ignored - but you can replace it with other flags (for example
