[v3-0-test] Unify selecting constraints option when installing airflow (#52274)
Due to the way how it historically got added - we had two ways of
selecting whether we are installing airlfow dyanmically in breeze
with or without constraints:

* --install-airflow-with-constraints - was used in a few places
* --skip-airflow-constraints - was used in other places

The logic to handle those were broken at places where they
contradicted each other. This PR unifies it and only uses
the --install-airflow-with-constraints flag in all the places
where we need to determine whether constraints are used or not
and it fixes the logic.

The logic of installation had been reviewed, refactored into
separate methods doing smaller tasks and more diagnostics was
added.
(cherry picked from commit 8846bef4f9cfc220ebf4aa68758ff798f0d17b05)

Co-authored-by: Jarek Potiuk <jarek@potiuk.com>

diff --git a/.github/workflows/ci-amd.yml b/.github/workflows/ci-amd.yml
--- a/.github/workflows/ci-amd.yml
+++ b/.github/workflows/ci-amd.yml
@@ -113,6 +113,7 @@ jobs:
       run-coverage: ${{ steps.source-run-info.outputs.run-coverage }}
       run-kubernetes-tests: ${{ steps.selective-checks.outputs.run-kubernetes-tests }}
       run-task-sdk-tests: ${{ steps.selective-checks.outputs.run-task-sdk-tests }}
+      run-go-sdk-tests: ${{ steps.selective-checks.outputs.run-go-sdk-tests }}
       run-system-tests: ${{ steps.selective-checks.outputs.run-system-tests }}
       run-tests: ${{ steps.selective-checks.outputs.run-tests }}
       run-ui-tests: ${{ steps.selective-checks.outputs.run-ui-tests }}
@@ -134,13 +135,13 @@ jobs:
         shell: bash
         run: docker run -v "${GITHUB_WORKSPACE}:/workspace" -u 0:0 bash -c "rm -rf /workspace/*"
       - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
-        uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
           persist-credentials: false
       - name: "Prepare and cleanup runner"
         run: ./scripts/ci/prepare_and_cleanup_runner.sh
       - name: Fetch incoming commit ${{ github.sha }} with its parent
-        uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
           ref: ${{ github.sha }}
           fetch-depth: 2
@@ -167,6 +168,37 @@ jobs:
         env:
           PR_LABELS: ${{ steps.source-run-info.outputs.pr-labels }}
           GITHUB_CONTEXT: ${{ toJson(github) }}
+
+  run-pin-versions-pre-commit:
+    name: "Run pin-versions pre-commit"
+    needs: [build-info]
+    runs-on: ${{ fromJSON(needs.build-info.outputs.amd-runners) }}
+    steps:
+      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+        with:
+          persist-credentials: false
+      - name: "Install Python 3.11 as 3.11+ is needed by pin-versions pre-commit"
+        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4.9.1
+        with:
+          python-version: 3.11
+          cache: "pip"
+      - name: Install pre-commit, uv, and pre-commit-uv
+        shell: bash
+        env:
+          UV_VERSION: "0.7.14"  # Keep this comment to allow automatic replacement of uv version
+          PRE_COMMIT_VERSION: "4.2.0"  # Keep this comment to allow automatic replacement of pre-commit version
+          PRE_COMMIT_UV_VERSION: "4.1.4"  # Keep this comment to allow automatic replacement of pre-commit-uv version
+        run: |
+          pip install uv==${UV_VERSION} || true
+          uv tool install pre-commit==${PRE_COMMIT_VERSION} --with uv==${UV_VERSION} \
+          --with pre-commit-uv==${PRE_COMMIT_UV_VERSION}
+      - name: "Run pin-versions pre-commit"
+        run: >
+          pre-commit run -c .github/.pre-commit-config.yaml --all-files --verbose --hook-stage manual
+          pin-versions
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   basic-tests:
     name: "Basic tests"
@@ -751,32 +783,71 @@ jobs:
       distribution-name: "task-sdk"
       distribution-cmd-format: "prepare-task-sdk-distributions"
       test-type: "task-sdk-tests"
+      use-local-venv: 'false'
     if: >
       ( needs.build-info.outputs.run-task-sdk-tests == 'true' ||
       needs.build-info.outputs.run-tests == 'true' &&
       needs.build-info.outputs.only-new-ui-files != 'true')
 
-  tests-airflow-ctl:
-    name: "Airflow CTL tests"
-    uses: ./.github/workflows/airflow-distributions-tests.yml
-    needs: [build-info, build-ci-images]
-    permissions:
-      contents: read
-      packages: read
-    with:
-      runners: ${{ needs.build-info.outputs.amd-runners }}
-      platform: "linux/amd64"
-      default-python-version: ${{ needs.build-info.outputs.default-python-version }}
-      python-versions: ${{ needs.build-info.outputs.python-versions }}
-      use-uv: ${{ needs.build-info.outputs.use-uv }}
-      canary-run: ${{ needs.build-info.outputs.canary-run }}
-      distribution-name: "airflow-ctl"
-      distribution-cmd-format: "prepare-airflow-ctl-distributions"
-      test-type: "airflow-ctl-tests"
-    if: >
-      ( needs.build-info.outputs.run-airflow-ctl-tests == 'true' ||
-      needs.build-info.outputs.run-tests == 'true' &&
-      needs.build-info.outputs.only-new-ui-files != 'true')
+#  tests-go-sdk:
+#    name: "Go SDK tests"
+#    needs: [build-info, build-ci-images]
+#    runs-on: ${{ fromJSON(needs.build-info.outputs.amd-runners) }}
+#    timeout-minutes: 15
+#    permissions:
+#      contents: read
+#      packages: read
+#    if: >
+#      ( needs.build-info.outputs.run-go-sdk-tests == 'true' ||
+#      needs.build-info.outputs.run-tests == 'true' &&
+#      needs.build-info.outputs.only-new-ui-files != 'true')
+#    env:
+#      GITHUB_REPOSITORY: ${{ github.repository }}
+#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      GITHUB_USERNAME: ${{ github.actor }}
+#      VERBOSE: "true"
+#    steps:
+#      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
+#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+#        with:
+#          persist-credentials: false
+#
+#      # keep this in sync with go.mod in go-sdk/
+#      - name: Setup Go
+#        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
+#        with:
+#          go-version: 1.24
+#          cache-dependency-path: go-sdk/go.sum
+#
+#      - name: "Cleanup dist files"
+#        run: rm -fv ./dist/*
+#
+#      - name: Run Go tests
+#        working-directory: ./go-sdk
+#        run: go test -v ./...
+#
+#  tests-airflow-ctl:
+#    name: "Airflow CTL tests"
+#    uses: ./.github/workflows/airflow-distributions-tests.yml
+#    needs: [build-info]
+#    permissions:
+#      contents: read
+#      packages: read
+#    with:
+#      runners: ${{ needs.build-info.outputs.amd-runners }}
+#      platform: "linux/amd64"
+#      default-python-version: ${{ needs.build-info.outputs.default-python-version }}
+#      python-versions: ${{ needs.build-info.outputs.python-versions }}
+#      use-uv: ${{ needs.build-info.outputs.use-uv }}
+#      canary-run: ${{ needs.build-info.outputs.canary-run }}
+#      distribution-name: "airflow-ctl"
+#      distribution-cmd-format: "prepare-airflow-ctl-distributions"
+#      test-type: "airflow-ctl-tests"
+#      use-local-venv: 'true'
+#    if: >
+#      ( needs.build-info.outputs.run-airflow-ctl-tests == 'true' ||
+#      needs.build-info.outputs.run-tests == 'true' &&
+#      needs.build-info.outputs.only-new-ui-files != 'true')
 
   finalize-tests:
     name: Finalize tests
@@ -829,6 +900,8 @@ jobs:
 
   notify-slack-failure:
     name: "Notify Slack on Failure"
+    needs:
+      - finalize-tests
     if: github.event_name == 'schedule' && failure() && github.run_attempt == 1
     runs-on: ["ubuntu-22.04"]
     steps:
@@ -846,7 +919,7 @@ jobs:
               - type: "section"
                 text:
                   type: "mrkdwn"
-                  text: "🚨🕒 Scheduled CI Failure Alert (AMD) on branch *${{ github.ref_name }}* 🕒🚨\n\n*Details:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View the failure log>"
+                  text: "🚨🕒 Scheduled CI Failure Alert (AMD) 🕒🚨\n\n*Details:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View the failure log>"
           # yamllint enable rule:line-length
 
   summarize-warnings:
@@ -859,7 +932,7 @@ jobs:
         shell: bash
         run: docker run -v "${GITHUB_WORKSPACE}:/workspace" -u 0:0 bash -c "rm -rf /workspace/*"
       - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
-        uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
           persist-credentials: false
       - name: "Prepare and cleanup runner"
@@ -868,12 +941,12 @@ jobs:
         shell: bash
         run: ./scripts/tools/free_up_disk_space.sh
       - name: "Download all test warning artifacts from the current build"
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
         with:
           path: ./artifacts
           pattern: test-warnings-*
       - name: "Setup python"
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
         with:
           python-version: ${{ inputs.default-python-version }}
       - name: "Summarize all warnings"
@@ -882,7 +955,7 @@ jobs:
             --pattern "**/warnings-*.txt" \
             --output ./files
       - name: "Upload artifact for summarized warnings"
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
         with:
           name: test-summarized-amd-runner-warnings
           path: ./files/warn-summary-*.txt
