Upgrade uv to 0.1.20 and stop notifying about new uv versions
The UV tool is iterating super-quickly with multiple releases a week
and until it slows down we do not want to be notified about every
release. Still in the CI the update will be running and we will be
able to see if there is a new version, but canary builds will not
fail when new version of uv is released. The build will fail when
a new version of `pip` is released and we will still be able to
update uv independently by running the same pre-commmit manually.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -623,15 +623,6 @@ jobs:
           --hook-stage manual
           update-build-dependencies
         if: always()
-      - name: "Run automated upgrade for installers"
-        run: >
-          pre-commit run
-          --all-files --show-diff-on-failure --color always --verbose
-          --hook-stage manual
-          update-installers
-        if: always()
-        env:
-          UPGRADE_UV: "true"
       - name: "Run automated upgrade for chart dependencies"
         run: >
           pre-commit run
@@ -639,6 +630,27 @@ jobs:
           --hook-stage manual
           update-chart-dependencies
         if: always()
+      # For UV we are not failing the upgrade installers check if it is updated because
+      # it is upgraded very frequently, so we want to manually upgrade it rather than
+      # get notified about it - until it stabilizes in 1.* version
+      - name: "Run automated upgrade for uv (open to see if new version is updated)"
+        run: >
+          pre-commit run
+          --all-files --show-diff-on-failure --color always --verbose
+          --hook-stage manual update-installers || true
+        if: always()
+        env:
+          UPGRADE_UV: "true"
+          UPGRADE_PIP: "false"
+      - name: "Run automated upgrade for pip"
+        run: >
+          pre-commit run
+          --all-files --show-diff-on-failure --color always --verbose
+          --hook-stage manual update-installers
+        if: always()
+        env:
+          UPGRADE_UV: "false"
+          UPGRADE_PIP: "true"
 
   mypy:
     name: "MyPy tests"
