Synchronize build scripts with main

diff --git a/.github/workflows/news-fragment.yml b/.github/workflows/news-fragment.yml
--- a/.github/workflows/news-fragment.yml
+++ b/.github/workflows/news-fragment.yml
@@ -21,7 +21,8 @@ name: CI
 on:  # yamllint disable-line rule:truthy
   pull_request:
     types: [labeled, unlabeled, opened, reopened, synchronize]
-
+permissions:
+  contents: read
 jobs:
   check-news-fragment:
     name: Check News Fragment
@@ -36,13 +37,15 @@ jobs:
           # needs a non-shallow clone.
           fetch-depth: 0
 
-      - name: Check news fragment
+      - name: Check news fragment existence
+        env:
+          BASE_REF: ${{ github.base_ref }}
         run: >
           python -m pip install --upgrade uv &&
           uv tool run towncrier check
           --dir .
           --config newsfragments/config.toml
-          --compare-with origin/${{ github.base_ref }}
+          --compare-with origin/${BASE_REF}
           ||
           {
           printf "\033[1;33mMissing significant newsfragment for PR labeled with
@@ -52,3 +55,28 @@ jobs:
           &&
           false
           ; }
+
+      - name: Check news fragment contains change types
+        env:
+          BASE_REF: ${{ github.base_ref }}
+        run: >
+          change_types=(
+            'DAG changes'
+            'Config changes'
+            'API changes'
+            'CLI changes'
+            'Behaviour changes'
+            'Plugin changes'
+            'Dependency change'
+          )
+          news_fragment_content=`git diff origin/${BASE_REF} newsfragments/*.significant.rst`
+
+          for type in "${change_types[@]}"; do
+            if [[ $news_fragment_content != *"$type"* ]]; then
+              printf "\033[1;33mMissing change type '$type' in significant newsfragment for PR labeled with
+              'airflow3.0:breaking'.\nCheck
+              https://github.com/apache/airflow/blob/main/contributing-docs/16_contribution_workflow.rst
+              for guidance.\033[m\n"
+              exit 1
+            fi
+          done
